version: 2.1
orbs:
  heroku: circleci/heroku@1.2.2
  docker: circleci/docker@1.4.0
jobs:
  deploy:
    executor: heroku/default
    steps:
      - setup_remote_docker
      - checkout
      - docker/install-docker
      - heroku/install
      - heroku/check-authentication
      - run:
          name: Heroku login
          command: 'heroku container:login'
      - run:
          name: Docker build
          command: 'docker build -t registry.heroku.com/${HEROKU_APP_NAME}/web .'
      - run:
          name: Push to Heroku
          command: 'docker push registry.heroku.com/${HEROKU_APP_NAME}/web'
      - run:
          name: Heroku release
          command: 'heroku container:release --app=${HEROKU_APP_NAME} web'

workflows:
  heroku_deploy:
    jobs:
      - deploy
