version: 2.1
orbs:
  heroku: circleci/heroku@1.2.2
  docker: circleci/docker@1.0.0
jobs:
  deploy:
    executor: heroku/default
    steps:
      - setup_remote_docker
      - checkout
      - docker/install-docker
      - heroku/install
      - heroku/check-authentication
      - run:
          name: Heroku login
          command: 'heroku container:login'
      - docker/build:
          registry: registry.heroku.com
          image: ${HEROKU_APP_NAME}/web
      - docker/push:
          registry: registry.heroku.com
          image: ${HEROKU_APP_NAME}/web
      - heroku/release-docker-image:
          process-types: web

workflows:
  heroku_deploy:
    jobs:
      - deploy
