version: 2.1
orbs:
  docker: circleci/docker@1.0.0
jobs:
  deploy:
    steps:
      - setup_remote_docker
      - checkout
      - docker/install-docker
workflows:
  heroku_deploy:
    jobs:
      - deploy
